usage:
  mandatory-flags:
    desc: The workflow does not define a default config (although examples are available), so you must provide your own.
    flags: --configfile
  software-stack-deployment:
    conda: true
    apptainer: false
    apptainer+conda: false
    report: false
